version: '3.1'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_budget_dev
    command: ['-c', 'max_connections=2000']
    ports:
      - '5432:5432'
